services:
  - type: web
    name: hcai-pbl
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn pbl.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.13.1"
