# Generated by Django 6.1 on 2026-09-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True)),
                ('arm', models.CharField(choices=[('pair', 'Design 1 - pairwise choice'), ('rank', 'Design 2 - rank ten')], max_length=8)),
                ('frequency', models.CharField(blank=True, choices=[('rarely', 'Less than once a month'), ('monthly', 'One to three films a month'), ('weekly', 'About one a week'), ('often', 'Several a week')], max_length=10)),
                ('seed', models.IntegerField()),
                ('preview', models.BooleanField(default=False)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('elicitation_seconds', models.FloatField(default=0.0)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('elicit', 'Elicitation'), ('holdout', 'Held-out test')], max_length=8)),
                ('position', models.IntegerField()),
                ('order', models.JSONField()),
                ('seconds', models.FloatField()),
                ('repeat_of', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project4.participant')),
            ],
            options={
                'ordering': ['participant', 'phase', 'position'],
                'constraints': [models.UniqueConstraint(fields=('participant', 'phase', 'position'), name='one_response_per_slot')],
            },
        ),
    ]
