# Generated by Django 6.1 on 2026-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=20)),
                ('algorithm', models.CharField(max_length=60)),
                ('param', models.CharField(max_length=40)),
                ('grid', models.CharField(max_length=300)),
                ('chosen', models.FloatField()),
                ('peak', models.FloatField()),
                ('rule', models.CharField(max_length=20)),
                ('score_name', models.CharField(max_length=40)),
                ('cv_score', models.FloatField()),
                ('test_score', models.FloatField()),
                ('test_fraction', models.FloatField()),
                ('n_folds', models.PositiveSmallIntegerField()),
                ('seed', models.IntegerField()),
                ('automated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
